#!/bin/bash

set -uo pipefail

hash restic &> /dev/null
[[ $? -ne 0 ]]\
    && echo "restic is not installed!"\
    && exit 1

backup_list="$(dirname $(realpath $0))/backup_list.sh"
[[ ! -f "$backup_list" ]]\
    && echo "Could not find list of folders to backup: $backup_list"\
    && exit 3

source $backup_list

set -e

CREDENTIALS=${CREDENTIALS:-'<user:pass>'}
REPO_NAME="$(whoami)@$(hostname)"
REPO_URL="${REPO:-rest:https://${CREDENTIALS}@restic.klingt.net/${REPO_NAME}}"

restic backup --repo "$REPO_URL"\
    --exclude "tmp/*"\
    --exclude "temp/*"\
    --exclude "Temp/*"\
    --exclude "cache*/"\
    --exclude "Cache*/"\
    ${folders[@]}\
    || echo "Does the repo exist? restic init --repo '$REPO_URL'"

# vim: filetype=sh
