#!/bin/bash

set -o pipefail

syncer=rsync
syncer_opts="--archive"
hash ${syncer} &>/dev/null
[[ $? -ne 0 ]]\
    && echo "${syncer} is not installed!"\
    && exit 2

sync_db() {
    local db_name="$1"
    local source="$2"
    local target="$3"
    ${syncer} ${syncer_opts} "$source/$db_name" "$target/$db_name"\
        && echo "Successfully synced to $target/$db_name"
}

keepass_db_name=${HOSTNAME}-${USER}.kdbx
keepass_db_dir=$HOME/vault
usbdrive="/run/media/${USER}/usbdata"

mount | grep $usbdrive &>/dev/null
[[ $? -ne 0 ]]\
    && echo "USB drive not present"\
    && exit 1

set -e

if [ "$1" == "--reverse" ]; then
    sync_db $keepass_db_name $usbdrive $keepass_db_dir
else
    sync_db $keepass_db_name $keepass_db_dir $usbdrive
fi

# vim: filetype=sh
