#!/bin/bash

set -euo pipefail

FILENAME="$HOME/Pictures/Screenshot-$(date +%s).png"

case "$1" in
'')
	maim "$FILENAME"
	;;
'select')
	maim --select "$FILENAME"
	;;
'window')
    maim --window=$(xdotool getactivewindow) "$FILENAME"
	;;
esac
